services:
  - type: web
    name: nexusnext-frontend
    env: node
    buildCommand: npm install; npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://backend-pms-obiy.onrender.com/api
